[package]
name = "day1"
version = "0.1.0"
authors = ["Tom Van Braband <tom.vanbraband@student.kuleuven.be>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
math = "0.0.2"